name: User-agent updater.

on:
  repository_dispatch:
    types: ["Restart user_agent_updater workflow."]
  schedule:
    # At 00:00 on day-of-month 1.
    - cron: "0 0 1 * *"

jobs:
  User-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: desktop-app/action_code_updater@0a8d3ebb437e5c77cf5d066d4a54cc93d34b534a # master
        with:
          type: "user-agent"
